# Copyright 2022-2024 the Kubeapps contributors.
# SPDX-License-Identifier: Apache-2.0

---
on:
  workflow_call:
    inputs:
      golang_version:
        type: string
        required: false
        default: "1.23"
      golangci_lint_version:
        type: string
        required: false
        default: "v2.5.0"
  workflow_dispatch:
    inputs:
      golang_version:
        type: string
        required: false
        default: "1.23"
        description: "Go version to use"
      golangci_lint_version:
        type: string
        required: false
        default: "v2.5.0"
        description: "golangci-lint version to use"

jobs:
  yaml-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - id: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
      - run: echo ${{ steps.yaml-lint.outputs.logfile }}
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: yamllint-logfile
          path: ${{ steps.yaml-lint.outputs.logfile }}

  golang-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.golang_version }}
      - uses: actions/checkout@v5
      - uses: golangci/golangci-lint-action@v8
        with:
          version: ${{ inputs.golangci_lint_version }}
          args: --timeout=10m

  license-headers-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v6
        with:
          go-version: ${{ inputs.golang_version }}
      - uses: actions/checkout@v5
      - name: Check license Headers
        uses: apache/skywalking-eyes/header@v0.6.0
