name: B&R dep Bitnami os-shell

on:
  workflow_dispatch:
  push:
    paths:
      - 'external/bitnami-deprecated-os-shell/12/debian-12/**'
      - '.github/workflows/release-bitnami-os-shell.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{ github.repository }}/bitnami-deprecated-os-shell
          tags: |
            type=raw,value=12-debian-12
            type=raw,value=latest

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: external/bitnami-deprecated-os-shell/12/debian-12
          file: external/bitnami-deprecated-os-shell/12/debian-12/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
